### ISSUE TITLE
Some todo items

### ISSUE THREAD

**Issue by awlauria** [awlauria/awlauria-tekton-demo#11]
- [ ]  Create a task to build an rpm with the sample app.
- [ ] Create a task to Install the rpm into a run container. Update the GitHub status to be 'installing'
- [ ] Create a task to run the app inside the run container. Update the GitHub status to be 'running'
- [ ] Wire in logic to update the status if a task fails. 
- [ ] Cleanup the pipeline.yaml file. There is some redundant code in there, and split these tasks to their own files with meaningful names.
